version: '1.0'
services:
  frontend:
    build: .
    container_name: load-balancer-advance
    ports:
      - "3000:3000"
    command: --backends "http://web1:80,http://web2:80,http://web3:80"
  web1:
    image: strm/helloworld-http
  web2:
    image: strm/helloworld-http
  web3:
    image: strm/helloworld-http